### ISSUE TITLE
Copy pasting either docker compose example not working after fixing volumes

### ISSUE THREAD

**Issue by Glynax** [Drazzilb08/userScripts#86]
I swear I'm just having a brain fart here but I keep getting 
 ✘ userscripts Error                                                                                                                                                             0.5s 
Error response from daemon: manifest unknown

when I try to pull or put the container up, not sure what I'm doing wrong.

---
version: "2.1"
services:
  userscripts:
    image: ghcr.io/drazzilb08/userscripts
    container_name: userscripts
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
    volumes:
      - /opt/userscripts/config:/config
      - /opt/plexmetamanager/assets/:/pmm
      - /opt/posters/:/posters
      - /opt/:/appdata
      - /mnt/mergerfs/data/media/:/media
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/mergerfs/data/Backups:/backup
    restart: unless-stopped

**Comment by Drazzilb08** [comment]
```yaml
services:
    userscripts:
        container_name: scripts
        network_mode: bridge
        environment:
            - TZ=America/Los_Angeles
            - HOST_CONTAINERNAME=scripts
            - PUID'='99
            - PGID'='100
        volumes:
            - /path/to/appdata/userscripts/':'/config':'rw
            - /path/to/data':'/data':'rw
            - /path/to/posters':'/posters':'rw
            - /path/to/backup':'/backup':'rw
            - /path/to/appdata/plex-meta-manager/assets/':'/pmm':'rw
            - /var/run/docker.sock':'/var/run/docker.sock':'rw
            - /path/to/appdata':'/appdata':'rw
        image: "'drazzilb08/userscripts:dev'"
      ```
      
Here is another one see if this works for you.. Lemme know.

**Comment by Glynax** [comment]
Sorry just seeing this now. 
![image](https://github.com/Drazzilb08/userScripts/assets/7043861/7b184944-78c7-4e69-9aa8-342c02f47d67)
Tried just changing the image and got a new error. Tried copy and pasting that entire thing EXACTLY and got an error as well. Any thoughts?

**Comment by Drazzilb08** [comment]
```yaml
services:
    userscripts:
        container_name: scripts
        network_mode: bridge
        environment:
            - TZ=America/Los_Angeles
            - HOST_CONTAINERNAME=scripts
            - PUID=99
            - PGID=100
        volumes:
            - /path/to/appdata/userscripts/:/config:rw
            - /path/to/data:/data:rw
            - /path/to/posters:/posters:rw
            - /path/to/backup:/backup:rw
            - /path/to/appdata/plex-meta-manager/assets/:/pmm:rw
            - /var/run/docker.sock:/var/run/docker.sock:rw
            - /path/to/appdata:/appdata:rw
        image: drazzilb08/userscripts:dev
```

Sorry I don't use compose so I'm not very versed in it..
